import { createContext, useContext, useState } from 'react';

const translations = {
  ru: {
    maps: 'Карты',
    editor: 'Редактор',
    exitEditor: 'Выйти из редактора',
    login: 'Вход в редактор',
    password: 'Введите пароль',
    wrongPassword: 'Неверный пароль',
    loginBtn: 'Войти',
    selectMap: 'Выберите карту',
    soon: 'Скоро',
    loading: 'Загрузка...',
    shiftHint: 'Shift+клик по карте - поставить конечную точку',
    throwType: 'Тип броска:',
    side: 'Сторона:',
    notSelected: 'Не выбрано',
    deleteTrajectory: 'Удалить траекторию',
    deleteVideo: 'Удалить видео',
    noVideo: 'Видео не добавлено',
    videoPlaceholder: 'Ссылка на видео (YouTube / Cloudinary)',
    groupGrenades: 'гранат',
    collapse: 'Свернуть',
    guide: 'Управление',
    guideClickMap: 'по карте - создать',
    guideClickMarker: 'по метке - редактировать',
    guideCtrl: 'в группу',
    guideShiftMarker: 'по метке - траектория',
    guideShiftMap: 'по карте - конец',
    guideRightClick: 'удалить',
    guideGroupClick: 'по группе - развернуть',
    guideDrag: 'Перетащить метку на другую - в группу',
    homeTitle: 'CS Lineups - Выберите карту',
    mapTitle: 'CS Lineups',
  },
  en: {
    maps: 'Maps',
    editor: 'Editor',
    exitEditor: 'Exit Editor',
    login: 'Editor Login',
    password: 'Enter password',
    wrongPassword: 'Wrong password',
    loginBtn: 'Login',
    selectMap: 'Select map',
    soon: 'Soon',
    loading: 'Loading...',
    shiftHint: 'Shift+click on map - set endpoint',
    throwType: 'Throw type:',
    side: 'Side:',
    notSelected: 'Not selected',
    deleteTrajectory: 'Delete trajectory',
    deleteVideo: 'Delete video',
    noVideo: 'No video added',
    videoPlaceholder: 'Video URL (YouTube / Cloudinary)',
    groupGrenades: 'grenades',
    collapse: 'Collapse',
    guide: 'Controls',
    guideClickMap: 'on map - create',
    guideClickMarker: 'on marker - edit',
    guideCtrl: 'add to group',
    guideShiftMarker: 'on marker - trajectory',
    guideShiftMap: 'on map - endpoint',
    guideRightClick: 'delete',
    guideGroupClick: 'on group - expand',
    guideDrag: 'Drag marker onto another - group',
    homeTitle: 'CS Lineups - Select map',
    mapTitle: 'CS Lineups',
  },
  es: {
    maps: 'Mapas',
    editor: 'Editor',
    exitEditor: 'Salir del editor',
    login: 'Inicio de sesión',
    password: 'Ingrese contraseña',
    wrongPassword: 'Contraseña incorrecta',
    loginBtn: 'Iniciar sesión',
    selectMap: 'Seleccionar mapa',
    soon: 'Pronto',
    loading: 'Cargando...',
    shiftHint: 'Shift+clic en el mapa - establecer punto final',
    throwType: 'Tipo de lanzamiento:',
    side: 'Lado:',
    notSelected: 'No seleccionado',
    deleteTrajectory: 'Eliminar trayectoria',
    deleteVideo: 'Eliminar video',
    noVideo: 'No hay video',
    videoPlaceholder: 'URL del video (YouTube / Cloudinary)',
    groupGrenades: 'granadas',
    collapse: 'Colapsar',
    guide: 'Controles',
    guideClickMap: 'en el mapa - crear',
    guideClickMarker: 'en el marcador - editar',
    guideCtrl: 'al grupo',
    guideShiftMarker: 'en el marcador - trayectoria',
    guideShiftMap: 'en el mapa - punto final',
    guideRightClick: 'eliminar',
    guideGroupClick: 'en el grupo - expandir',
    guideDrag: 'Arrastrar marcador sobre otro - agrupar',
    homeTitle: 'CS Lineups - Seleccionar mapa',
    mapTitle: 'CS Lineups',
  },
  de: {
    maps: 'Karten',
    editor: 'Editor',
    exitEditor: 'Editor verlassen',
    login: 'Editor Login',
    password: 'Passwort eingeben',
    wrongPassword: 'Falsches Passwort',
    loginBtn: 'Anmelden',
    selectMap: 'Karte wählen',
    soon: 'Bald',
    loading: 'Laden...',
    shiftHint: 'Shift+Klick auf Karte - Endpunkt setzen',
    throwType: 'Wurftyp:',
    side: 'Seite:',
    notSelected: 'Nicht ausgewählt',
    deleteTrajectory: 'Trajektorie löschen',
    deleteVideo: 'Video löschen',
    noVideo: 'Kein Video',
    videoPlaceholder: 'Video URL (YouTube / Cloudinary)',
    groupGrenades: 'Granaten',
    collapse: 'Einklappen',
    guide: 'Steuerung',
    guideClickMap: 'auf Karte - erstellen',
    guideClickMarker: 'auf Marker - bearbeiten',
    guideCtrl: 'zur Gruppe',
    guideShiftMarker: 'auf Marker - Trajektorie',
    guideShiftMap: 'auf Karte - Endpunkt',
    guideRightClick: 'löschen',
    guideGroupClick: 'auf Gruppe - erweitern',
    guideDrag: 'Marker auf anderen ziehen - gruppieren',
    homeTitle: 'CS Lineups - Karte wählen',
    mapTitle: 'CS Lineups',
  },
  fr: {
    maps: 'Cartes',
    editor: 'Éditeur',
    exitEditor: 'Quitter l\'éditeur',
    login: 'Connexion éditeur',
    password: 'Entrez le mot de passe',
    wrongPassword: 'Mot de passe incorrect',
    loginBtn: 'Connexion',
    selectMap: 'Choisir une carte',
    soon: 'Bientôt',
    loading: 'Chargement...',
    shiftHint: 'Shift+clic sur la carte - définir le point final',
    throwType: 'Type de lancer:',
    side: 'Côté:',
    notSelected: 'Non sélectionné',
    deleteTrajectory: 'Supprimer la trajectoire',
    deleteVideo: 'Supprimer la vidéo',
    noVideo: 'Aucune vidéo',
    videoPlaceholder: 'URL de la vidéo (YouTube / Cloudinary)',
    groupGrenades: 'grenades',
    collapse: 'Réduire',
    guide: 'Contrôles',
    guideClickMap: 'sur la carte - créer',
    guideClickMarker: 'sur le marqueur - modifier',
    guideCtrl: 'au groupe',
    guideShiftMarker: 'sur le marqueur - trajectoire',
    guideShiftMap: 'sur la carte - point final',
    guideRightClick: 'supprimer',
    guideGroupClick: 'sur le groupe - développer',
    guideDrag: 'Faites glisser le marqueur sur un autre - grouper',
    homeTitle: 'CS Lineups - Choisir une carte',
    mapTitle: 'CS Lineups',
  },
  pt: {
    maps: 'Mapas',
    editor: 'Editor',
    exitEditor: 'Sair do editor',
    login: 'Login do editor',
    password: 'Digite a senha',
    wrongPassword: 'Senha incorreta',
    loginBtn: 'Entrar',
    selectMap: 'Selecionar mapa',
    soon: 'Em breve',
    loading: 'Carregando...',
    shiftHint: 'Shift+clique no mapa - definir ponto final',
    throwType: 'Tipo de lançamento:',
    side: 'Lado:',
    notSelected: 'Não selecionado',
    deleteTrajectory: 'Excluir trajetória',
    deleteVideo: 'Excluir vídeo',
    noVideo: 'Nenhum vídeo',
    videoPlaceholder: 'URL do vídeo (YouTube / Cloudinary)',
    groupGrenades: 'granadas',
    collapse: 'Recolher',
    guide: 'Controles',
    guideClickMap: 'no mapa - criar',
    guideClickMarker: 'no marcador - editar',
    guideCtrl: 'ao grupo',
    guideShiftMarker: 'no marcador - trajetória',
    guideShiftMap: 'no mapa - ponto final',
    guideRightClick: 'excluir',
    guideGroupClick: 'no grupo - expandir',
    guideDrag: 'Arraste o marcador sobre outro - agrupar',
    homeTitle: 'CS Lineups - Selecionar mapa',
    mapTitle: 'CS Lineups',
  },
  zh: {
    maps: '地图',
    editor: '编辑器',
    exitEditor: '退出编辑器',
    login: '编辑器登录',
    password: '输入密码',
    wrongPassword: '密码错误',
    loginBtn: '登录',
    selectMap: '选择地图',
    soon: '即将推出',
    loading: '加载中...',
    shiftHint: 'Shift+点击地图 - 设置终点',
    throwType: '投掷类型:',
    side: '阵营:',
    notSelected: '未选择',
    deleteTrajectory: '删除轨迹',
    deleteVideo: '删除视频',
    noVideo: '未添加视频',
    videoPlaceholder: '视频链接 (YouTube / Cloudinary)',
    groupGrenades: '个投掷物',
    collapse: '收起',
    guide: '操作指南',
    guideClickMap: '点击地图 - 创建',
    guideClickMarker: '点击标记 - 编辑',
    guideCtrl: '加入组',
    guideShiftMarker: '点击标记 - 轨迹',
    guideShiftMap: '点击地图 - 终点',
    guideRightClick: '删除',
    guideGroupClick: '点击组 - 展开',
    guideDrag: '拖动标记到另一个上 - 成组',
    homeTitle: 'CS Lineups - 选择地图',
    mapTitle: 'CS Lineups',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en');

  const changeLang = (newLang) => {
    setLang(newLang);
    localStorage.setItem('lang', newLang);
  };

  const t = (key) => translations[lang]?.[key] || translations['en']?.[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}